inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "test/**/test_*.rb"
    - "examples/**/test/**/test_*.rb"
    - "**/.toys.rb"

Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Style/ModuleFunction:
  Enabled: false
